// <Auto-Generated></Auto-Generated>

using System;
using System.Threading.Tasks;

using Cuture.Extensions.Modularity;

using SampleModule4;

namespace SampleModule2
{
    //此时将会替换模块4中的Module4Helloable
    [ExportSingletonServices(AddDIMode.Replace, typeof(IHelloable))]
    public class Module2Helloable : IHelloable
    {
        private string _assemblyName;

        public string SayHello()
        {
            return $"Hello 这里替换了其它的{nameof(IHelloable)} . 这里是 {_assemblyName}";
        }

        public async Task InitAsync()
        {
            Console.WriteLine($"Init {nameof(Module2Helloable)}");
            await Task.Delay(TimeSpan.FromSeconds(1));
            _assemblyName = typeof(Module2Helloable).Assembly.GetName().Name;
        }
    }
}
