// <Auto-Generated></Auto-Generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

using Microsoft.Extensions.DependencyInjection;

using SampleModule2;

using SampleModule4;

namespace WebApiHostSample.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class TestController : ControllerBase
    {
        private readonly IHelloable _helloable;
        private readonly IAccessCounter _accessCounter;
        private readonly IRequestRandomProvider _randomProvider;

        public TestController(IHelloable helloable, IAccessCounter accessCounter, IRequestRandomProvider randomProvider)
        {
            _helloable = helloable;
            _accessCounter = accessCounter;
            _randomProvider = randomProvider;
        }

        [HttpGet]
        public object Get()
        {
            _accessCounter.Add();
            return new
            {
                hello = _helloable.SayHello(),
                accessCount = _accessCounter.Count,
                scopedRandom1 = _randomProvider.Random(),
                scopedRandom2 = _randomProvider.Random(),
                random1 = HttpContext.RequestServices.GetService<IRandomProvider>().Random(),
                random2 = HttpContext.RequestServices.GetService<IRandomProvider>().Random(),
            };
        }
    }
}
