// <Auto-Generated></Auto-Generated>

namespace Cuture.Extensions.Modularity
{
    /// <inheritdoc cref="ISyncAppModule"/>
    public abstract class AppModule : ISyncAppModule
    {
        /// <inheritdoc/>
        public virtual void PreConfigureServices(ServiceConfigurationContext context)
        {
        }

        /// <inheritdoc/>
        public virtual void ConfigureServices(ServiceConfigurationContext context)
        {
        }

        /// <inheritdoc/>
        public virtual void PostConfigureServices(ServiceConfigurationContext context)
        {
        }

        /// <inheritdoc/>
        public virtual void OnPreApplicationInitialization(ApplicationInitializationContext context)
        {
        }

        /// <inheritdoc/>
        public virtual void OnApplicationInitialization(ApplicationInitializationContext context)
        {
        }

        /// <inheritdoc/>
        public virtual void OnPostApplicationInitialization(ApplicationInitializationContext context)
        {
        }

        /// <inheritdoc/>
        public virtual void OnApplicationShutdown(ApplicationShutdownContext context)
        {
        }
    }
}