// <Auto-Generated></Auto-Generated>

using Microsoft.Extensions.DependencyInjection;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace DependencyInjection.Modularity.Test;

[TestClass]
public abstract class DIContainerTestBase
{
    protected IServiceCollection Services { get; set; }

    [TestInitialize]
    public virtual void InitDIContainer()
    {
        Services = new ServiceCollection();
    }
}
