// <Auto-Generated></Auto-Generated>

using System;
using System.IO;

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace UseHostSample
{
    class Program
    {
        static void Main(string[] args)
        {
            var module3Path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "SampleModule3.dll");
            var module5Directory = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "plugins");

            //直接在HostBuilder加载，或者使用ConfigureServices进行加载
            Host.CreateDefaultBuilder(args)
                .LoadModule<HostSampleModule>()
                .LoadModuleFile(module3Path) //从文件加载
                .LoadModuleDirectory(source =>
                {
                    source.SearchDepth = 5;    //设置文件夹搜索深度
                }, module5Directory)  //从文件夹加载
                .ModuleLoadComplete()
                .UseConsoleLifetime()
                .InitializationModules()
                .Run();
        }
    }
}
