// <Auto-Generated></Auto-Generated>

namespace Cuture.Extensions.Modularity
{
    /// <summary>
    /// <inheritdoc cref="IAppModule"/>生命周期接口 - <inheritdoc cref="ConfigureServices"/>
    /// </summary>
    public interface IConfigureServices
    {
        /// <summary>
        /// 配置服务
        /// </summary>
        void ConfigureServices(ServiceConfigurationContext context);
    }
}
