// <Auto-Generated></Auto-Generated>

namespace Cuture.Extensions.Modularity;

/// <summary>
/// <inheritdoc cref="IAppModule"/>生命周期接口 - <inheritdoc cref="ConfigureServicesAsync"/>
/// </summary>
public interface IConfigureServicesAsync
{
    /// <summary>
    /// 配置服务（包含异步操作）
    /// </summary>
    Task ConfigureServicesAsync(ServiceConfigurationContext context);
}
