// <Auto-Generated></Auto-Generated>

namespace Cuture.Extensions.Modularity
{
    /// <summary>
    /// <inheritdoc cref="IAppModule"/>生命周期接口 - <inheritdoc cref="OnApplicationInitialization"/>
    /// </summary>
    public interface IOnApplicationInitialization
    {
        /// <summary>
        /// 初始化应用
        /// </summary>
        /// <param name="context"></param>
        void OnApplicationInitialization(ApplicationInitializationContext context);
    }
}
