// <Auto-Generated></Auto-Generated>

namespace Cuture.Extensions.Modularity
{
    /// <summary>
    /// <inheritdoc cref="IAppModule"/>生命周期接口 - <inheritdoc cref="OnApplicationShutdown"/>
    /// </summary>
    public interface IOnApplicationShutdown
    {
        /// <summary>
        /// 应用关闭
        /// </summary>
        /// <param name="context"></param>
        void OnApplicationShutdown(ApplicationShutdownContext context);
    }
}
