// <Auto-Generated></Auto-Generated>

using System.Threading;
using System.Threading.Tasks;

namespace Cuture.Extensions.Modularity
{
    /// <summary>
    /// <inheritdoc cref="IAppModule"/>生命周期接口 - <inheritdoc cref="OnApplicationShutdownAsync"/>
    /// </summary>
    public interface IOnApplicationShutdownAsync
    {
        /// <summary>
        /// 应用关闭（包含异步操作）
        /// </summary>
        /// <param name="context"></param>
        /// <param name="token">关闭的超时Token</param>
        /// <returns></returns>
        Task OnApplicationShutdownAsync(ApplicationShutdownContext context, CancellationToken token);
    }
}
