// <Auto-Generated></Auto-Generated>

namespace Cuture.Extensions.Modularity;

/// <summary>
/// <inheritdoc cref="IAppModule"/>生命周期接口 - <inheritdoc cref="OnApplicationInitializationAsync"/>
/// </summary>
public interface IOnApplicationInitializationAsync
{
    /// <summary>
    /// 初始化应用（包含异步操作）
    /// </summary>
    /// <param name="context"></param>
    Task OnApplicationInitializationAsync(ApplicationInitializationContext context);
}
