// <Auto-Generated></Auto-Generated>

namespace Cuture.Extensions.Modularity;

/// <summary>
/// <inheritdoc cref="IAppModule"/>生命周期接口 - <inheritdoc cref="OnPreApplicationInitialization"/>
/// </summary>
public interface IOnPreApplicationInitialization
{
    /// <summary>
    /// 初始化应用前
    /// </summary>
    /// <param name="context"></param>
    void OnPreApplicationInitialization(ApplicationInitializationContext context);
}
