// <Auto-Generated></Auto-Generated>

namespace Cuture.Extensions.Modularity
{
    /// <summary>
    /// <inheritdoc cref="IAppModule"/>生命周期接口 - <inheritdoc cref="OnPostApplicationInitialization"/>
    /// </summary>
    public interface IOnPostApplicationInitialization
    {
        /// <summary>
        /// 初始化应用后
        /// </summary>
        /// <param name="context"></param>
        void OnPostApplicationInitialization(ApplicationInitializationContext context);
    }
}
