// <Auto-Generated></Auto-Generated>

namespace Cuture.Extensions.Modularity;

/// <summary>
/// <inheritdoc cref="IAppModule"/>生命周期接口 - <inheritdoc cref="PostConfigureServicesAsync"/>
/// </summary>
public interface IPostConfigureServicesAsync
{
    /// <summary>
    /// 配置服务后（包含异步操作）
    /// </summary>
    Task PostConfigureServicesAsync(ServiceConfigurationContext context);
}
