// <Auto-Generated></Auto-Generated>

namespace Cuture.Extensions.Modularity;

/// <summary>
/// <inheritdoc cref="IAppModule"/>生命周期接口 - <inheritdoc cref="PostConfigureServices"/>
/// </summary>
public interface IPostConfigureServices
{
    /// <summary>
    /// 配置服务后
    /// </summary>
    void PostConfigureServices(ServiceConfigurationContext context);
}
