// <Auto-Generated></Auto-Generated>

namespace Cuture.Extensions.Modularity
{
    /// <summary>
    /// <inheritdoc cref="IAppModule"/>生命周期接口 - <inheritdoc cref="PreConfigureServices"/>
    /// </summary>
    public interface IPreConfigureServices
    {
        /// <summary>
        /// 配置服务前
        /// </summary>
        void PreConfigureServices(ServiceConfigurationContext context);
    }
}