// <Auto-Generated></Auto-Generated>

namespace Cuture.Extensions.Modularity;

/// <summary>
/// <inheritdoc cref="IAppModule"/>生命周期接口 - <inheritdoc cref="PreConfigureServicesAsync"/>
/// </summary>
public interface IPreConfigureServicesAsync
{
    /// <summary>
    /// 配置服务前（包含异步操作）
    /// </summary>
    Task PreConfigureServicesAsync(ServiceConfigurationContext context);
}
