// <Auto-Generated></Auto-Generated>

using System.Reflection;
using System.Threading.Tasks;

using Microsoft.Extensions.DependencyInjection;

namespace Cuture.Extensions.Modularity
{
    /// <summary>
    /// 模块引导拦截器
    /// </summary>
    public interface IModulesBootstrapInterceptor
    {
        /// <summary>
        /// 从程序集中注册服务中
        /// </summary>
        /// <param name="services"></param>
        /// <param name="assembly"></param>
        /// <returns>返回false则中断后续操作</returns>
        Task<bool> RegisteringServicesInAssemblyAsync(IServiceCollection services, Assembly assembly);
    }
}